---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./bazarr/ks.yaml
  - ./bazarr4k/ks.yaml
  #- ./lidarr/ks.yaml
  - ./prowlarr/ks.yaml
  - ./radarr/ks.yaml
  - ./radarr4k/ks.yaml
  - ./sonarr/ks.yaml
  - ./sonarr4k/ks.yaml
  - ./tautulli/ks.yaml
  - ./overseerr/ks.yaml
  #- ./plex/ks.yaml
  - ./readarr/ks.yaml
  - ./recyclarr/ks.yaml
