---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app sonarr4k
  namespace: media
spec:
  interval: 16m
  chart:
    spec:
      chart: app-template
      version: 1.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: ghcr.io/onedr0p/sonarr-develop
      tag: rolling
    env:
      TZ: Europe/Stockholm
      SONARR__INSTANCE_NAME: Sonarr4k
      SONARR__PORT: &port 80
      SONARR__LOG_LEVEL: info
    service:
      main:
        ports:
          http:
            port: *port
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header Accept-Encoding "";
            sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://theme-park.ekenhome.se/css/base/sonarr/nord.css"></head>';
            sub_filter_once on;
          hajimari.io/icon: mdi:television-classic
        hosts:
          - host: &host "{{ .Release.Name }}.ekenhome.se"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 100
    persistence:
      config:
        enabled: true
        existingClaim: sonarr4k-config-pvc
        mountPath: /config
      media:
        enabled: true
        type: nfs
        server: 192.168.50.50
        path: /mnt/user/Media/series4k
        mountPath: /media
      downloads:
        enabled: true
        type: nfs
        server: 192.168.50.50
        path: /mnt/user/Downloads/
        mountPath: /data
    resources:
      requests:
        cpu: 10m
        memory: 250Mi
      limits:
        memory: 2000Mi
