apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: databases
stringData:
    username: ENC[AES256_GCM,data:KGNqaK8=,iv:cQiuix6CXriLDtdpHYK6qJ7htt9znM9+UOfUtMywRzY=,tag:GEMCHIUGYUpBWDXgUIdt1A==,type:str]
    password: ENC[AES256_GCM,data:jleWnqQtrq9stqu+FMLJLw==,iv:IHjRRgC5JgutSzurVPbtincLI4BbGjQGck1zy72h6R0=,tag:PSgkuPEEN1UcUnWWtTNVyg==,type:str]
    POSTGRES_SUPER_USER: ENC[AES256_GCM,data:0eFJ7aE=,iv:i65xxS3Uzx2Pql1hD7uaxXCdVg7yAyDLBaEFwmJ1p3Q=,tag:r9eSqZSUck6RGEXRk7u++Q==,type:str]
    POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:tdOu/5ZToGQ=,iv:DJ5/RwN1bVGL2LFj5hzx3ScCbetoxxqSo/YmbQxf5O4=,tag:xkqRjoH79l4M/lfVXQh7vA==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:gQTnl8K+pi8=,iv:ort84++RTSgur2AIL5wLfRWnXwm7rhzLGVRvJcWItnQ=,tag:69q8EaNS4rTtfBPim4aNBw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ElPbIv0Wock=,iv:gpZ07T7zuloFkJvy9e2+Mxjfz7UVKH3dimO8LJjPxVs=,tag:ONDmxrzaAS8LFbVJHk4pcg==,type:str]
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:lsJC+XvMYy8G29U5itJWDQ==,iv:pe85OQk8rqzritBnv3h42aArDrNAtCufIojN+vU3u1A=,tag:kFJ3/fRSPFG2oJ4xHVUqYQ==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:eUZ1PWBsRi9TwSL2itJKiJAIU5WecJxNhrY3DyLuWBM=,iv:ffITjRNVKPdQv4VZz7/39Y9HFh0n97Rr8Z11Fibmoh0=,tag:PXbDvGj1RaHCUeLT8P4zuQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18xqz4vdtp26yq4u0u2rkh78w9s3us74d3247a2kcjn9qn4t8hqzsrghccm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOVTArNksxeWc3b0dXR0ZG
            RXFuZ2xJM3FoWmVPdW1ZOW1LQ2QyRmRHaHg0CkhVdWZ2RTVMczIvOGdEQ2VEV1JS
            NDgveThrOFF1VGFjL3Q0bHY4ZllrVFUKLS0tIDFVY09XM2UwUHFGNXdBQVQ3R0M5
            MStMdDI0YkZKR0dxTTJXUkhhcUhDdlkKepPXvDujZt6TseVj4s9FjsNa/3LzjxjA
            KhuiP8Iu0LYUGw5rZtyML7B9Tnanmo0cmYXcfiFu37KU+OMwFg9Sgw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-23T13:59:29Z"
    mac: ENC[AES256_GCM,data:oXLW72GHCtAObj8jwflnxfdH6Tfm7kCtT685TiY5Ax/iV3hJgOyt8/wxjtsyMe6T03kMz1+c+jpV0oDUCQxkce9IEbANMBhqyuC8yk+0cpjQ/9qetUvqmTTocqbIYPoHUyvO9EseIWCtOUVcHdMJQVqHLaSOSpP8vuZlK5qQvSc=,iv:AibFYMYbzVEIbPpTxOyLsi1dAAvw4T/GPsL7yzb+20k=,tag:v2QdW9lRTf573EZIO0Ne+w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
