apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: databases
stringData:
    username: ENC[AES256_GCM,data:KGNqaK8=,iv:cQiuix6CXriLDtdpHYK6qJ7htt9znM9+UOfUtMywRzY=,tag:GEMCHIUGYUpBWDXgUIdt1A==,type:str]
    password: ENC[AES256_GCM,data:jleWnqQtrq9stqu+FMLJLw==,iv:IHjRRgC5JgutSzurVPbtincLI4BbGjQGck1zy72h6R0=,tag:PSgkuPEEN1UcUnWWtTNVyg==,type:str]
    POSTGRES_SUPER_USER: ENC[AES256_GCM,data:0eFJ7aE=,iv:i65xxS3Uzx2Pql1hD7uaxXCdVg7yAyDLBaEFwmJ1p3Q=,tag:r9eSqZSUck6RGEXRk7u++Q==,type:str]
    POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:tdOu/5ZToGQ=,iv:DJ5/RwN1bVGL2LFj5hzx3ScCbetoxxqSo/YmbQxf5O4=,tag:xkqRjoH79l4M/lfVXQh7vA==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:gQTnl8K+pi8=,iv:ort84++RTSgur2AIL5wLfRWnXwm7rhzLGVRvJcWItnQ=,tag:69q8EaNS4rTtfBPim4aNBw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ElPbIv0Wock=,iv:gpZ07T7zuloFkJvy9e2+Mxjfz7UVKH3dimO8LJjPxVs=,tag:ONDmxrzaAS8LFbVJHk4pcg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18xqz4vdtp26yq4u0u2rkh78w9s3us74d3247a2kcjn9qn4t8hqzsrghccm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOVTArNksxeWc3b0dXR0ZG
            RXFuZ2xJM3FoWmVPdW1ZOW1LQ2QyRmRHaHg0CkhVdWZ2RTVMczIvOGdEQ2VEV1JS
            NDgveThrOFF1VGFjL3Q0bHY4ZllrVFUKLS0tIDFVY09XM2UwUHFGNXdBQVQ3R0M5
            MStMdDI0YkZKR0dxTTJXUkhhcUhDdlkKepPXvDujZt6TseVj4s9FjsNa/3LzjxjA
            KhuiP8Iu0LYUGw5rZtyML7B9Tnanmo0cmYXcfiFu37KU+OMwFg9Sgw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-20T15:29:13Z"
    mac: ENC[AES256_GCM,data:2PkEIjYom7ZU97WVhvIoilM5wJGPlZ1NXo6VPHtiBZMBq/4VIre9a5I1zkowmw7rH0g1K5HYOzbqvSp7EntvQQQjH1PgfJGKo1EsufR7NGoJ+6pijeFCUsGFkdVUdvThd4jDgf9Nu5En7RBMVWf6jRgZFXnFlJ6sNBpEhRzAWb8=,iv:fIfzmtXxSR088oMLty3ZTWqW8Hpdo8hTNJBFDbTFzX0=,tag:ofExko9fUEdToAeLiPR64A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
