kind: ENC[AES256_GCM,data:DkmhbDtT,iv:K/CUfnhUhyDXvh1GEfQ6iuHncEfJmzP7RzqTiyjWpuA=,tag:Y1Uh/UnhnaZBpxO43GkpVA==,type:str]
ansible_user: ENC[AES256_GCM,data:/nsJV+WK,iv:anBdydkV7hw/fPlOVc5gU+OSfuFCDFFOR1mrhh0zL7c=,tag:VZWDxbgPljDmOXVmYCTXJQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:Q1dhVZe5Nts=,iv:0Ciz7sZ1+AfsNImRnlHN0mQGZKbi1YeYEvCxEJBqzhI=,tag:y/H/TQjJIego4ZH8O7ewyw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18xqz4vdtp26yq4u0u2rkh78w9s3us74d3247a2kcjn9qn4t8hqzsrghccm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYSnA3R0c4RGZiSjR5UUZC
            TXpjVUVibThxTlp5QWxzY21wMldmYzlNcndrCnkxWktESUNtVHZ5a0ZtWmFTeTBJ
            OTc4YSs1TEduMkdoRGRxQkJMODBNUUkKLS0tIFZLY05rcnoxWkFoK3hKd1pJU2th
            MVBjV3dRbEpRWEdvN3FOMlNSaEx6ZDgK6qY3sKTwPml0xZeE9McK03YH6iP6CyMl
            9iYN4zWuSsgRkegN38WiKv1PoLgQRE/wm3bAJV75NO44qKwQ2HhvKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-23T13:28:04Z"
    mac: ENC[AES256_GCM,data:05L7gV6l00API+1Sw69yj1uy5BhjCrqLcEwkPxyx+Ck/WQ23aqtnY7bqeDt4Z6/4uCMn/dAJ2T+SpbAC9CMIJV6I+ZsX8R9slsWKbiiTnbJAxQ1xbFRYwxznJpFLkwENbnp5x1C9qe1bM0dAVjcgJXmfToTyEGDuqQf6b6XbdJU=,iv:HBcylLrFbLkj5s7Xqm9o7Kq/a+ig1Oqefgo4dwWioGU=,tag:pX0TwWBQkorbCwiUm6awkQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
