kind: ENC[AES256_GCM,data:MsFVM/Ol,iv:ZOwTa1A+sQSfr3Wk8hOK499udVeSAXNPK2pucGXCmx8=,tag:CrslrCrQ5nOUuRXMZSDFJA==,type:str]
ansible_user: ENC[AES256_GCM,data:0D6vW8yJ,iv:ZffiHjgJl7c51PqtpCSqKKp16tsHqmc932XP8Y9brxg=,tag:jFdNjq0CIPuSp1KdkArOkQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:SFvfBu2X6Ms=,iv:jk0mJ6F1lovx9ojsmgHrQyzRdWWI6Rerq88aDWma2eU=,tag:VqQWKnlppHv5qKTk8oCC7Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18xqz4vdtp26yq4u0u2rkh78w9s3us74d3247a2kcjn9qn4t8hqzsrghccm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVR1dnNFFQVEVQZnNmdFpr
            VENCa1A0ZlQ2TGVKQkxmT1luWlNtVnpDY2w4CnFqVi9TUkp5R0dHWWVFVXZRcXdr
            dFRiemV6MnF6T2VianFnbmdkYXBvb2cKLS0tIDZFeWI5RWwrQnovY3hWaUhTRVQv
            RVRnQUZQcG53SnFjU3JyZk0xOTVFUkUK0QHFG1ErqRgsKl2cXDnFJeGfzF+hABbv
            LcQxVbhFAtaXpCVTI6zGuWxXf2lQI8nLrOT4j30iSDh97PjufFl6KA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-13T13:03:37Z"
    mac: ENC[AES256_GCM,data:X7NcESv4NmA17lK5iaazJCCGJcuZAhECvXyybV3hxtE+fcN8HwVLY4I7R0K8aDAmfpW3tHGCRSycKAXQcg9C/K+hmMR0R9I/dfx4PW+AdG6N4UkrCZVcT4wsLC7x8nfqUJ6ZsmYLCWFDxb0+xKHmCRhrYIHGp4H8MJbot7GRM78=,iv:swk6aoUw3Is7pceZtNWvdxFQ6nY/K0vGrztYAmaVTRg=,tag:GcC4ss+9TWGNuvoVeMvoLg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
