kind: ENC[AES256_GCM,data:8Y2AMbD9,iv:Et4u+7JynPYzQLuzEEJyvaDalev16N7JG7M1dC0HYHk=,tag:0dUAQcSOBD0NDEIHwZyjDg==,type:str]
ansible_user: ENC[AES256_GCM,data:bat8KBwP,iv:+fg4AkbE+0bUA1VImZ6iCa9twyTGR/B7H00Qi010HeU=,tag:u8cwOR5NNdc0gZBAx215OQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:a1NloXwk+GY=,iv:WsrDUF7VGj7knsTWFvbC5lbyFXws36eoFPPdiFz3USc=,tag:vFoAmi6t2Fof+bIp8yYT+w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18xqz4vdtp26yq4u0u2rkh78w9s3us74d3247a2kcjn9qn4t8hqzsrghccm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLdFBqZXUwSStwMGFDRHRl
            clhZdjV6WTBUc0JlVFpxRzFZQmk2WTFmS1IwCml1NVhHY0l2TlN6RzIvSGZzQ1Js
            Ni91WWtJejJoMjZYMTdla2l0clZJcWsKLS0tIFBxRTB3YWMvdFlnSzdGVkFTaW04
            c3Q1NzQwcy9QRDFvTXZlMzFkSVJvTFUKgSNCnT9BI3I1aoWBhHEtqQjH+dsK1lEz
            Tt6a+SUM3INAueNZuL9I88iLsOZblOAa93OG8InQeEutp1faNjZIGQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-23T13:28:04Z"
    mac: ENC[AES256_GCM,data:nI4xs1Z5dI4AIUbMUPfWwQaMT8dU/rta76/tpDJ0La0YG3GcWZDU4htQtQYMC5MnT/5cWLK5D4zAPO09fSdWZ8/8WtpcQzMGlb6kkXB0yePr4LnAN1b/fJVKdxbYFqOJ6tqJ3awlH+gXPT90VD3F+xCQM2q+qpaPM6yBiL3tCBM=,iv:t7pVmPEDpxtwvPDw5ZkZLbtIV4oxA/6mytxxasRFEBw=,tag:a3PjX/QbKz2La5JV0Lmo0w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
