kind: ENC[AES256_GCM,data:0kaNzgE2,iv:kRYAlXldRJoLE2xU9BdiKSq6OTpShD65bRWOT0a0lSg=,tag:bRhSnMpF1QdOQO4OjET99A==,type:str]
ansible_user: ENC[AES256_GCM,data:S5ldh5Nu,iv:0KhAMcCATGLzz3CN5HiqgvshFXkhUaHCwO44ijBy4qE=,tag:WBHQGdgh6QbMRS5vGo77tQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:Pyfv7UuCvl8=,iv:cdDewBhgShcrOnXXwjRTg2xSPOCWusRtBJbHjdKNOCY=,tag:8mZ2OaUufdByLH97cTyBiw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18xqz4vdtp26yq4u0u2rkh78w9s3us74d3247a2kcjn9qn4t8hqzsrghccm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4S1lkSWlrSHg0LzY0c3Er
            cmUyakc3WEI4a2s1aTRnZWVrLzRrbU1RQWpJCi8vR0hWMXhEWW5ka0tPYWdTMzZL
            ckJScVZmSDl1ZHMvbUNvRlU5UnJlVWsKLS0tIEF6LzltdzFoMjB2aUoxRi9MNThx
            a1gzcVpjdW93NnBzL0lJR1R5b0ZsSHcKDum/3W7LKLJpq+86x37+qWh2xXUiJ25y
            /GfxHxNKDP78Er0MAoIq5lnW0xK8shTUamNa1NQoJvczahATs8DIXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-07T00:02:55Z"
    mac: ENC[AES256_GCM,data:fdG7tD3Z42aQI+rzsFDzDJE8NDhlMoq+PcKV7EfXHzdl+6bcrn0uoMAlf0BxCZx5Ufen39hZOS6NZnGScoyep4bC6rRz/b/O4hdyj5oQ9H4SqiFF1M2/o8siT4H9w6cvXRw4tdhp1JD17Ct2JcSzGqSDFiHHNVIIntwjTkfZR0g=,iv:VIUmxN58If9K6sYeJKwXqB1HWipceOl8R1goix8GEl4=,tag:svTy9Pmb7KvVMEZKfKuzVg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
