kind: ENC[AES256_GCM,data:dW9/klz7,iv:UZl5LDepcLYJGciQGSV9bwOa491p0hZVRFuZhf7cfNc=,tag:GoIvSe9qtwFL54MUtEx5Rw==,type:str]
ansible_user: ENC[AES256_GCM,data:SBSU6qp9,iv:FMVFHn2yBUrLez6yN2tY94K/HIB/mGEODKijTlUBQXs=,tag:iBa5whnnMnuDH13I8ujo+w==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:IImD6mWDLME=,iv:NMAAnRSdUebHEPk5ZYTuivkiM2XeGpn2potp5bLqtnc=,tag:JREKQZMNI8AAAdD9zOMa7A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18xqz4vdtp26yq4u0u2rkh78w9s3us74d3247a2kcjn9qn4t8hqzsrghccm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvUmxCRGpyU1pVZkVrS20v
            WG8ydDYvTzZBbjFpSk9NZDZ5amZVbkFXQ0c0Cjh3d1I1MHcrTmhDYytSaXFDcDlv
            RHZVMDNpU1lBMHF5NnlRTFMrZWkvZDQKLS0tIDA3ajVMWXFHUUJMMS9KVElWU0hO
            SWRGUFd3ZVN6SHRaaERBNG9zZjBXaWcKlyGEZiAz3yvseUAPkOj9k/m1a1poUFy6
            WcooG5PKctkZYcR7kMbyiJJ6lHZnzDCFyxDTDnBoMn2Gr9C3VxLAPg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-12T22:41:52Z"
    mac: ENC[AES256_GCM,data:RH8j5kCgXopXFdfib/yHvZOjPZRYuz1klaV52kaqEQB7xgvKNNMHsagvVYSpI2pqkeRbKULviThsi6yQg+7FyJ+sw3avliJlWN9PadH0AaccZu0e7sPLq6uIbat4bMIH5u0K/vKZ/DAO0vWQh0y5C/bx5aFqCd84b8tpNOdw9A0=,iv:mk/CN2PFrbEUrYYbrlZ/SNk7lWssBt10gukh1zwbHRQ=,tag:5ME15JT630amehyff+V1Xw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
