kind: ENC[AES256_GCM,data:S9R3iC1/,iv:6IXJEQdmu6JsN+93X4NVi6QdNqaBnnbB+bcOHf1p5LI=,tag:AxP8FZfTrhWgV6x5s/w8qg==,type:str]
ansible_user: ENC[AES256_GCM,data:ZTCrLvdh,iv:ehi44Z+0eZ0tmiGu7mBJZ29GRrC56yRxrCA6Aefmz34=,tag:cx96r+KM8uUPX0fLRUKbng==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:zkrZ16VlYkk=,iv:7+D/ayv5Q9j3TDEMIhuwWi+dzmMFZdo5ajoaONBCmgE=,tag:FU1OPjkU6imRmXGax4pr5w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18xqz4vdtp26yq4u0u2rkh78w9s3us74d3247a2kcjn9qn4t8hqzsrghccm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOZzI1VmU4RGVRQ210SjVk
            RllaS3JoTjBncEhjUmlRZWR6Q1VBU2JNSlQwCnV3RWxCbFJ0czc0Y2h1WVh1K3RO
            M1BQL0Z5TzJINTdzcE5xWEZkUnlER0kKLS0tIGFBdXVIbTFRRDBQYUhQclhzSW5r
            V2RoK0IyM29DWUZLaE1iWFVnYzY2dDgK+/hzK9bLfzapvqZSdGq45jn3WeIC1ja3
            2a3oVQp0Auq2K4vvM+iOj6swGBR6PaGU2zbzSk3FR5uZQsjEU4Ni2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-12T22:41:52Z"
    mac: ENC[AES256_GCM,data:NoRWLUrNvvag0FjCWk0Q36x+V3ijCFiGyAAIb+9Tg005dYJ/1SpXd/et17A+YiwxDwkVSU4QSwkY/LVewtPAZWX9waXsSvqoMEYrQvCOfGNe4c0KjKUSokdQQSL7fte/c7EUsmMrmrtLBhHfDR9/NJWtokg7WhTgC56Brj9XvKA=,iv:hsdgAVRXFYS9hLBCYCKuomvBX0qrdBp5DfHINulveBw=,tag:+M0zF6meZilAK9Zyjmo3xg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
