kind: ENC[AES256_GCM,data:IMUS0g1k,iv:KxQdguHwwusJx8NKDfz+dvxKprM8wgnmq9riBt3RDl4=,tag:KJtu0hiqCSmupf5HSNFF0g==,type:str]
ansible_user: ENC[AES256_GCM,data:puYOGdvu,iv:4YaLsRWrUIoibskn9rRd5fBFD3OCd/vOg7Z6YSv/V0k=,tag:8APa6hHoDxZcBt/1mZR4OA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:ZhtCxYTztbU=,iv:5hn28M9cr+I0Py64pY1wtrzrqEieVnQKwqJaCiGILM4=,tag:rd7/22LhYnZtY7HyDT3CJQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18xqz4vdtp26yq4u0u2rkh78w9s3us74d3247a2kcjn9qn4t8hqzsrghccm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXM2c0UkJIWlRTL0ZDOExj
            WWFIYy9ZdnI4MENKRnNuVE4xNVcwaGdrVG1rCjRvMFZ4WGVzUXBUcEV6SlhXUTdk
            d0FsZVpoWGV3ZXMvM2lkODR6ZjBwd0kKLS0tIE96T2FLUTh4czVnQTFpVmtQOVRr
            MUFpZjVwdXhweEs5eHZ4S1dKN2U3S0UKlyEaW4qHYU50tprdlVlr97S0i2DYZmM0
            nGi0B0yrECYtXB+1wtE1pLNhv4gDg2IJn/D3wrPuZ1Kz3ZejGF2FCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-12T22:41:52Z"
    mac: ENC[AES256_GCM,data:c7pZ9YulpY6rNusZKPFcg+fTm237rMgQ3BnfBBBO7UJxlYAARvt9PrmwEu/IC6KgjMhkHbQGv/Dzm3O6cjOVV5yduXU/JRtgtNEv7exs0zKUdyJ2zIsiOUQVr32Rb/tD3MzQXkiz9tCoBEgA6Pd2xF6nLLmdD8RLigmFv5yOieU=,iv:wOVLiChtWL47kYifEdFCjDt4eN6f6uPuu3BD/17wdsw=,tag:T1xChvvJ4Y+nz/Lu66pE4A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
