kind: ENC[AES256_GCM,data:OYdeaZ0o,iv:o7d+q3XFQZWzUSXwMP0uRtH1X6wcOslnMPR5s6zqLSA=,tag:gs+3Ksm/zvxAgtudeTD+SA==,type:str]
ansible_user: ENC[AES256_GCM,data:xFCPAL7d,iv:5MvPZIYZH2WP/4LA7/NsKYLRGHB0eMJqPUVQNYpiw58=,tag:3RRp+g+ZwkllzWo34NOTfw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:CLz3FqishpI=,iv:J24wScvwZXrEk9YIs7zCU8CvJ6QzrekP6Oqq4+g8z2Q=,tag:17fezS5C3/eX2DlR4SII2w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18xqz4vdtp26yq4u0u2rkh78w9s3us74d3247a2kcjn9qn4t8hqzsrghccm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZVjJzb1pPV0MrRDAvcDli
            Sk9VZ2ZyaEhKYnFkSnI3TGduTTF2Rnpua2o4Cng5Ymk3OGVqeEdRMUQyOTdaSnov
            R0ExejdzRnFNR3BWbWpVaDduWFF4cjQKLS0tIDlWRE0wYjVjM3I2ai9vZHNsWnA2
            Q2MyQTJFNmNvQUR3bDk3SmNRamxYdFkKKDiPUNiRqVa9UKxik6y+6dhJS2rxNMNU
            FANXSv56kvu5LaY6qfn1eSdT2tCUTQ2M+ROJQ9g8rVf4Xu1UdrZ89Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-23T13:28:04Z"
    mac: ENC[AES256_GCM,data:eSh+4Kpr0A10yXLbdP7VT0NPMrvfgtNnpZpdbccyIB5dlGNq11OwB22TFItvv7M4yVrZOJYUtRb+qFGVa78q2aLkHF0QSB0bhxvCFDL/Nve5xTy8s0iv88pX7O94xAd3DpF2UDkoHtyr4d+KLXSLZmo8e8Zvov70f/icOo1q+v8=,iv:esSMU1MzArD8q3LMquPqHeWWQjPZKr6yalnh9UR+NEo=,tag:45IV7f2LCKEtkrdLg0YWZQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
