kind: ENC[AES256_GCM,data:6ecK5Hwd,iv:UXzDARMrvj138dCiucYM/cv1MopUQpOI54MMqbcq5E4=,tag:je2FT7di+tcIU8iitGWQyQ==,type:str]
ansible_user: ENC[AES256_GCM,data:p1kmFvJ+,iv:LTfdNn9yOgab8WJWSzAhAAIJybaFNATX8PnvFQ+CA1U=,tag:JbLiRBH0jslkqjvqBv4Ttw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:QTFrxCUcoP4=,iv:ktOS/CvQzNaPuDlT2ZwuS7jbWhpeq3m9beK6JT+VwRY=,tag:5/64hj9nMD88LvrxIQSvaA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18xqz4vdtp26yq4u0u2rkh78w9s3us74d3247a2kcjn9qn4t8hqzsrghccm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBV1VXMmwwTFZNWFpIdHBQ
            UUhVa29GdmJTa0JyN1huckU3MkxwMDFERnhzCjFmV0hqNndXU1FHWGtDSDd2aTFT
            bk5ZakpyWm5FMnU5aHN0anhZS2NmbjAKLS0tIHVvcTlRQnZKeWJJbWVETkZZL016
            K2tyTHFvSFE0eE9KQWVjK1kxYXdvbWsKhv6Dd0QVJHoQod+/M6euqSDN1w5UcvJE
            BkncoIxCqNjNbFwoIneNdTvoJfzq7vVXtJtxU2P7ziBThFbgOV4bSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-23T13:28:04Z"
    mac: ENC[AES256_GCM,data:6Y/eMtrqeK+/pHYnk0KisRm2z2SCypFzxG36du54hlfmVLvNu/oYN1nA8dlnfMpYzt11atQDYBsDEozWvR1hXN09uxgy2K7qk9bieN7V2H89gskKvIEteBfQfeZJT5dhp+Ta6/VRhka4sscWe6Ui9kr0RQXDrwZz38/GJozgIdw=,iv:f3peJul/+pPWA9JZ4/zFaT2PaTQqDqw5rA4JZbs0mlY=,tag:yBuDEpOwJKbNCw1zg7G4aQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
