kind: ENC[AES256_GCM,data:3ZHN4piG,iv:WAEPSLS8lpVe0gyNqo2lLBfi8/0J3Apz+Zj+pxEKmV0=,tag:fgpxRyy/DyBXUEH6C1TQHA==,type:str]
ansible_user: ENC[AES256_GCM,data:WE9HQnjL,iv:rgVvqny3HPu/Cpxl01wtNe8wi6qs32eDwFgRGAWVZfk=,tag:kyfQYDAQlQ/12A9blLShkg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:5IxthV7hmLE=,iv:VhGKbVAfV1PpxH1xLPdD+fgvrWKMe1QuJNSPHvbv3Z0=,tag:sAQaUw4qp5rdtHJkoIY6jQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18xqz4vdtp26yq4u0u2rkh78w9s3us74d3247a2kcjn9qn4t8hqzsrghccm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvWmdLR0pZUjhmRzRuWDcv
            K1RRb2UwSmdLZmYwVmk5MWExYzVmK3psdDJzCnl4TjR3MEUrUVI2ejZXVCtUSUd5
            Q1RDVzVzTjNXOFBWWDVRVVFVdloyaUUKLS0tIHMyM2VETnV1Q0l6c1NTVGZlbU51
            RGVta1FNUytxaWVhRjVGcFV3NTRWVTAK29D81Uxfggqg/TnXivDwQvd4zuaEzNpA
            DglAGOVsL5qXS2aumpUkh9O8mLOxEErBdhu1TKIRiEn63sSeCWee3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-13T13:03:37Z"
    mac: ENC[AES256_GCM,data:YjfKMs/A7Z6fzVcfAppg0FRqOk/tDjiiTF4MNqGbjr3oqamuRA3AlvRcnIKSkI0IFMJWNn8ZbGi97Ke6l7Wmos55431kabAVqfPdduDV1d4Cf8vRuKC6Vmc5vGzIB1lldCVGUFxiPCXrta8g1RYGfHq+Ma0Z+ukrNseUSyl8QVM=,iv:9bKtAhnwzJF1nGcM+YlJgZkSCuY2Z0iusKQEULa/Rc8=,tag:96rgnm0s+OAYh61r0v7rEw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
