apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:AeuGuwA+u0zPYmRCkc0Om60fVwb8BYRRKgt2sxojKyU3d8Z9uoug6g==,iv:kcRrgGz0AEUPRIm868MAOHw68/V2ywLiXWZ33t+cf6g=,tag:JJ+MRLVu2aubqjSM+pIF8Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18xqz4vdtp26yq4u0u2rkh78w9s3us74d3247a2kcjn9qn4t8hqzsrghccm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDZUZFRnlXRmUvZk5sVzZv
            cXM2Y1NQNDNCUVpnMEMyRlppL3cvZXZTVjBVCldsYUR0T1NQaGU1OUVQeWNPQmtQ
            QnlHbHVMKzE5Snpobmg4Wm1TTkhybncKLS0tIGpwQUhDZjMzcGg1S0huY3ZjdnNz
            ME40b2lXSjc3K2JzMFk2NzlCckNRQjAKOYUCQUVU7zlEN6pzTgiEdBjrfKUgld4x
            jYjTqPcRXObDVn+gZMIrnyd+0/GaviiMDKeW9Q/jjsWVw7g02MdF6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-12T23:30:31Z"
    mac: ENC[AES256_GCM,data:opcT8pYobS06eM3XcfmM6CwbcnYtEFf8kIVWKswuo+BwYw6VGL26+5Brbv5pTOkVAXnuToHe8Mc7fi1fP5IXkr2VJUYL//1sx0CKkSX4sJ3SHcxvAWsjAeRxu3DNZZdFEpt3tVa/EuvSzggt9H1r1QaEQL+lGTTiF/jtopuOXvQ=,iv:K4BU+ZC7aCjxxnMyZLmiKyveUytzy6LgadYbCtxu+L0=,tag:C9VL31cz5r748WtD6hooAg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
