apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:GDXp3gZ3u8nqLh+iSDoXUg92aPFAqXzCUVeUladwIa71Mv/NBL7fhQ==,iv:+OZ7XT1BqXq1Ue/9h1xtPt1dH7LqHHU1r7UCScihiDI=,tag:uT1mZAdvhUzUanusfImkMg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18xqz4vdtp26yq4u0u2rkh78w9s3us74d3247a2kcjn9qn4t8hqzsrghccm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSaWxQd1FIbHR6d1BKVUtB
            NytDanNpbWlkSkxaMjJSdVQwVWxydTVpRVdZCkhDS2FaWFlCZjFuMzNlYzkrbXNP
            WW1LM3hITHAvd1RGdFBvbjBzMEFYc1UKLS0tIFBSRms1Y2gyYXJsUll5QXREQ0Jk
            ejNaeG0rR0VZRk9UV01mZCsxd21PbEEK7wULMVvmjgwCbHFkQNimkjh8vLKm48Ay
            PXYJXRa5unzUI7BEmPuWtkiJTcwtVyjthXy/oSD7+g43JAUh4HQNnw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-23T13:28:04Z"
    mac: ENC[AES256_GCM,data:08NPApFpBoQrocA5A6Lht9Fdm4HGJNyVOFJQFvXSVKHJ3gZIXp9hsGKnfroaDafS6k4AeYrFbe/xEyn2fGnOEviI/T6Io5Jm9XRzqqGbNGbVjmyK7wn0mHWPlAnqPW7qLsyBBtqbCJ9n3b5zqs8yEs9KK8MIUlWDzT9cstJNPLs=,iv:V1QmHD+2AXWT72BXayFlXqYMA+lJrSrem5/Fr7DMbVs=,tag:VZNjBX/qvVl7iIhH04DTkA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
