apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:9lCZ18shOfUB+Y7snI40s/c6u1SloD7CVOrtR5Ge886Uwhfcv4fYEA==,iv:QkCGvpDu/l0HrcXKHV+z7DsjOFZsCN7rTnwm+KB8hjs=,tag:KPrTjbAfEROyzAtvMKcf3g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18xqz4vdtp26yq4u0u2rkh78w9s3us74d3247a2kcjn9qn4t8hqzsrghccm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYRnBSWWV3Z250MGZLek5a
            WUlQMzcvRG9IZDVnVFIvSkJURUovb3ZlVkRrCnhGSHRPOTdNTldoZHBTVmRucllr
            R2NYbU5QN3JIS0k5eGJ6eDBkUXdwOUkKLS0tIE9mQkRNVzQxUCtaOU9jenlncUh6
            WSs1MDhjT0FNVUxtZk9wVXl0TnhxWUUKf3gfXJhkFswbMOLGffOLSZthvjvbUeAh
            pJsG6vz8LZWMFZ5xCcH/yr3WYscqfMQMMVI7LhF/aiwWQHgUSeQpuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-13T13:03:37Z"
    mac: ENC[AES256_GCM,data:bHza3+kHJ7rlj68D7tFH/mfznKla20d19zdeM+knt8Ya6RYx3EMlLrqrm3FUTy4xNsySGYEMDnG4AqV3pkbKi1x8Y6cWvnBMlDSUb3HsB2sVXwlFsvCGhP43aYxkTMaKQZ/FUs/4hCBYdLmUKsKR87qKnyrQ81nTFWzG9V2b7/s=,iv:J0LxceR+z2b39iqxFr+M6UgaOu04w3WON3xY8OtDnJE=,tag:HFJS7CITWCrrWWCF6q4T3Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
