apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:1rY8ftkZZsyxccPSiZCXBbqiFvv365eCnhEvY/UNErbi+gTM0/E0zw==,iv:M1xwwbzxiUeQRlNQRZ7EZbVivkqgkGOiIvoNyw2zRhU=,tag:9ldAqOHvvgbzKt60Jk94Nw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18xqz4vdtp26yq4u0u2rkh78w9s3us74d3247a2kcjn9qn4t8hqzsrghccm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjQVY1bnlYN09DWHo3S29Z
            b0tYby9LL2FlWWNNSWtCQTBLQll5ajMvOENNClUvb3RxdzJVdmdMa1BlZ0pMVnRY
            bjBQc2srazQxYmFWQURZa3pTWUcyQkUKLS0tIG9kTUJiS1ZxUWFPdmxnVU9tUUtp
            UVpEZ3JaQzZMTEl1WFdMdmo5dGlDK2MKZsVZWzXzWP3OrU2l73xIFoHeQ156JNSG
            os/RYTEfzZSmx3WFRhLnlAz1U5E2hs9SjGpkSwpu69LX9MS3e1QOIw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-12T22:41:52Z"
    mac: ENC[AES256_GCM,data:wQwkLdTR5pjsIkd55al5nq47LtFHx/r1RtG443T4EhxnwZA4yaTNFZlgKntAOzQRyykmQFom6jNdw+xk2/E7JEtLDFIef3pRwlsWvhNN+GTq21ZeOEDzQC7kDf5WlFHoU8ftwgeKMJ6ux/CwwlvcuZet9OOnkvh1+OVqQkswKZM=,iv:PASf3MEV9XskX62epEeURHa0c6TsfpHXyHC8m/2AlgM=,tag:sWNBBRrbfAtpfnsyX8L9lQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
