---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 15m
  chart:
    spec:
      chart: longhorn
      version: 1.4.0
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    persistence:
      defaultClassReplicaCount: 3
    defaultSettings:
      defaultReplicaCount: 3
      createDefaultDiskLabeledNodes: true
      storageMinimalAvailablePercentage: "10"
      defaultLonghornStaticStorageClass: "longhorn"
      backupTarget: "s3://k3s-longhorn@eu-west-1/"
      backupTargetCredentialSecret: minio-secret
      defaultDataPath: "/home"
    ingress:
      enabled: true
      ingressClassName: "nginx"
      tls: true
      host: "longhorn.${SECRET_DOMAIN}"
      tlsSecret: "longhorn-${SECRET_DOMAIN}-tls"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        hajimari.io/enable: "true"
        hajimari.io/icon: "content-save-outline"
