apiVersion: v1
kind: Secret
metadata:
    name: minio-secret
    namespace: longhorn-system
type: Opaque
stringData:
    AWS_ENDPOINTS: http://192.168.1.16:9768
    AWS_ACCESS_KEY_ID: longhorn
    AWS_SECRET_ACCESS_KEY: striker3
