apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:HGBACNjm0/Vy2JsqvWc8gL1c5qh1zi9C/6kDCxi6qf6+Z4QNow==,iv:6kX1aOqWy7YeDXtQOHlxadgsiotuWPbxQxj1Tos1U7A=,tag:lq271s62PwX+m7tPJyF52A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18xqz4vdtp26yq4u0u2rkh78w9s3us74d3247a2kcjn9qn4t8hqzsrghccm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCTkVqZ1VreVkvS2JRSWlx
            YTN2OUI4RWZsdnVSSmZiOVJMQlUzVGc3dWhZCmZZdWZkNGd1eEZZVFlOZ1Qwa0gy
            SlB1N0hqSE01VTVNSngweXdOSnl6TW8KLS0tIDk0RnZJNGxMRnJVSm5KZHhiL21C
            OHlVcDdwb3BiRHdKQ21ZN3Q1OXhUcU0KF7/gpvnL33r5WA1MftLbCUCeslwWyEMG
            7XERnfhq59NKQFsPK9QfLD1EnjXNnvM82yfKZLF9kkW1ADfyQiFpnw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-07T00:02:55Z"
    mac: ENC[AES256_GCM,data:RDco3BBd/LIo8Ym0X/LEhmkAYVUS+b6/iZSRlumT5nlBaypjns90DoyWGnkv9RnAP6oxjktEPUr6e0JKn0eYlzXk6cCm9bdJ+r1/IxwiGXBqg+3AjKt/2zkZ5bILMBHNqBcqSpQZmGHCdu1/fdVNYo4zAjD8v1YWzmR9XEYF1Zo=,iv:72SxrV7KR9pKijE1Lk3VHiDBDzvqdEtgorAnzt6WJCk=,tag:dhwTXM8cxdCD4wx5Vk7MbA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
