apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:E3ckGrR3r6/sM0pmTs4jNRL9ppVSXvJUXo4d9URI6vFejBj6Jw==,iv:ZXW1qDeA1bKYBfG/tvbFOPGDQBhFgXRYD5at60AqAxU=,tag:xHHTdj9LLWdsQ4snwx/1Pw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18xqz4vdtp26yq4u0u2rkh78w9s3us74d3247a2kcjn9qn4t8hqzsrghccm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaZ21oQkNHQ0FaM0FqYnVU
            VU03Z1FQajZHN1BsOGJCR3F2ekNRZlVydERvClg4dlRXNGdwYTE3MnVGdWhwM0pw
            T2FoUGd3YUJhYWRVMktsUzh2VU5JNzQKLS0tIE9IVVFzbTl6SGNUeURsSXNOQWwx
            cGJET2JBQ1lwbVp1VzJRbWdtY3A3SHcKw3mxU54YXP/Jb3pzPyJexsBD8Cv2e7rz
            fJ03KuJbXnaM+iVm3TGbCPd3E560+Cln5Fm6nTOsKb97ygeddKimRA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-06T22:34:08Z"
    mac: ENC[AES256_GCM,data:1OpHZgu71H1C215FTZ+lpUgiQp3hD5OGcl5KVHs5GtxcqGaEwJUm2ffo8Qm6TPbp+jmBx6Xpw89l7JRf2I6AzlqYe1TrgBl2z4gCHFoRimkuJScrTDLMEdnjX0BiOGkUu6PuKP9ApjY3/iBjt0IX9oSeuxGlgDZPbG9dxpCt5CY=,iv:DvsY7TASp/8PQnvcgi9Whb7X5kAnpbpOnVZb+zZABaE=,tag:cWhtOnL82qqmNKcFgtuEcg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
