apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:p8enWVGGPFz35ryl78Kvcg4sqV7RPHJXrC5mR0HpzF2iamtl2w==,iv:Y/AAlPEWi5zAxUNfmfgWZEQtvub14CW8LYIo59n0IWI=,tag:qpWRRKbqMaujyeUWdpNrYA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18xqz4vdtp26yq4u0u2rkh78w9s3us74d3247a2kcjn9qn4t8hqzsrghccm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtVWpTQ0hJODQ0TXYzWnNV
            WUthTlNCUWtBamVuSVM4dVgxQTQ1czJ4YkZNCjBYd2hZL3J4WVYzRHdLUUVXU2FI
            TUhMNGpiWVNSa0N1UmZZS1JtNXBUcXcKLS0tIEM2WFhpOCtoZGw2R0JZNkUxbkpR
            RTlWQ0ZOM3l3d3RkYkVEOHdkd09VYjAKKlOxRavLRpJ6AwumOTnSZkSrVGFi2lFt
            YVEmgSC6lxxuAQ/EY0o3YXDylE2ageJIy/VrQHicU1juXCzdRVkQfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-23T13:28:03Z"
    mac: ENC[AES256_GCM,data:dmOk4KS9ZhvU4EXtvWGQ1lF/mABka6w82zpbOBXC5HWWXiydpFJImloS5lXX+aMw5kHvZyswToXQpQOC2QFog9aNuxVR43JWjO8e2N+BEw5HmisJBHrtrNOEpH08Mu/jp5oaE7kjp4yBIulf7xcj6g2JsvjTgdr/FT+nHWB7/1w=,iv:LH7vKl0NyknHtA/8JbXQ7WQ17rW9cTVvGaOXuCFQVD4=,tag:e01fQ7rfwK2x6ieGWjgifQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
