apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:+JmRmi9IEkd225x9iOhXjQObLVESwzpieeLhTDD/S2NCFhw2nQ==,iv:nME9Ud+sZD/aNz6YehOTXJKGuKY0JaWPUV4xVbGZAMY=,tag:aY0xQrxcOquAxte6Tva6Mw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18xqz4vdtp26yq4u0u2rkh78w9s3us74d3247a2kcjn9qn4t8hqzsrghccm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmU3gyRk9rWnhTbGlGYUhD
            WU52aW9qZkl1UGxFMGpoQWlUbk54YlVEOVNFCnlrSkZYMVVxT01vZzFrREw4WjBl
            WXdUOG5iUS9vQXlEU0pyNzZBRHVkTlUKLS0tIGxrQ1BoSkVOOUQybklrUVV6VjBt
            OU5lUHRTQ3JYdHdwRHVjWGJDbDROTUkKywaxzM4aFb9Y8tcw9jrYRP/n9/yGiAXc
            pU9iw90zst9eXxgPkLbP5LZRITGqP2X11gdYMhO8nzbFl3biYYF4Vg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-12T23:30:31Z"
    mac: ENC[AES256_GCM,data:VMgQZL58MFgBRDPnwY76pvXbthlUNyfJ7NYMBsM2ljWrnRL8wl2Raj1AkVpCLNn9hulQPcGmSO9UCgW9NtW9YpfbQXilbSSY1bH1rLL9oSxN5ll0DrGJfFmMSfJlhMGWzhOvLgNvmwcqJ2umlgk5VTQHqL9DRKcsN35Qu+aNe/A=,iv:V/6Pu0+V+78KGNxfipdYcrTljhcSCJy7KBkeQeL0p1U=,tag:vbcwJL8netedgaek15vc1w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
