---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-nfs
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  storageClassName: minio-nfs
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "192.168.50.50"
    path: /mnt/apps-backup/
  mountOptions:
    - nfsvers=4.2
    - nconnect=8
    - hard
    - noatime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-nfs
  namespace: databases
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: minio-nfs
  resources:
    requests:
      storage: 1Mi
