apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: minio-secret
    namespace: databases
stringData:
    MINIO_PROMETHEUS_TOKEN: ENC[AES256_GCM,data:vT3L88AA,iv:NlM9qsSmED6eRBIWgH/Auwg0v/MWr1lj9vGs04U51OU=,tag:ry2qa0N3ezhrnOaOUXPULA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18xqz4vdtp26yq4u0u2rkh78w9s3us74d3247a2kcjn9qn4t8hqzsrghccm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVc2VWbThUY1dEaG4zcHpS
            SXg1Z1FzamZzcXlvejF6SDdGMUJXNmVqdHhZCnFSYlp4c3Mzc2MxUHRqc0crNEFB
            cUpuTXkwNG5TRjFiUC96UFFVQWFwUDAKLS0tIHBaaUQ2MXl5ekpLcktKZDlkM2hw
            MFp5MjBncU9hSTRpVk13STFOWk5jTzAKap8eW5hpNB41+OErhk+TEwq1kSnH6vSg
            R18XqToC5pRTvyTpqtslHLB4HJlO50XHP+MSvTdTW4W5cKqE/YsNow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-12T11:16:02Z"
    mac: ENC[AES256_GCM,data:Z5ttkgDckuttPCcQ12dkRw+n7PqFKbryrab+yp0juO7Z/FL9SLLFMaICcvA8DQM2sOhxah9BDq1pYOVwZvpmx/bSNN9GhvdfRmdsXKCUa+TOy4Ftr5GoGwlA4BgdSsKiLcpuPdKArOiJxDy7bs6adUGeHroUeJNkhbUf+TsJfRE=,iv:TvViDx83sBXGg6gZ6mjpuXVtX0ICy2GGO+dxD3Ki7qk=,tag:7dDzXq8L/RzeoRPBAKBOwQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
