apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: minio-secret
    namespace: databases
stringData:
    MINIO_PROMETHEUS_TOKEN: ENC[AES256_GCM,data:VoeWCP0=,iv:m5OhX8CE1+svoa/yo0DssVf1A/+IVTXJeDDvXmDpcT0=,tag:j0n2ImJx0q1iPe6d4vWyvQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18xqz4vdtp26yq4u0u2rkh78w9s3us74d3247a2kcjn9qn4t8hqzsrghccm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVc2VWbThUY1dEaG4zcHpS
            SXg1Z1FzamZzcXlvejF6SDdGMUJXNmVqdHhZCnFSYlp4c3Mzc2MxUHRqc0crNEFB
            cUpuTXkwNG5TRjFiUC96UFFVQWFwUDAKLS0tIHBaaUQ2MXl5ekpLcktKZDlkM2hw
            MFp5MjBncU9hSTRpVk13STFOWk5jTzAKap8eW5hpNB41+OErhk+TEwq1kSnH6vSg
            R18XqToC5pRTvyTpqtslHLB4HJlO50XHP+MSvTdTW4W5cKqE/YsNow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-12T11:18:36Z"
    mac: ENC[AES256_GCM,data:hCOHbYITuhc1bSHHj/7ZCvs6oF6dr4CnC+5YkVHrm9wXab0enSEO05o2B0dydBky5akqIs1C024rUFJREDoqeiDb6PpKA/38vAc9J9mTDPs4BLtQNoqUG4Lps4I8xkT4dS2dUCAIrLve8CKgTI2rr8b/iTjgQ9P/XewHUficrwM=,iv:w0QV414UP3SyuK7/+POnn1ild3K5XLrDza7Q0DIrY2M=,tag:yMaUHd9FJXyM9GuS37/ihA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
