apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: minio-secret
    namespace: databases
stringData:
    MINIO_PROMETHEUS_TOKEN: ENC[AES256_GCM,data:/3XMJ3E=,iv:arNHZTlIKiPXDxh3mdeqUdDqVPzEChLMg5jfz6oJsBY=,tag:01dHbNA3u8UX2AbfzztaJA==,type:int]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18xqz4vdtp26yq4u0u2rkh78w9s3us74d3247a2kcjn9qn4t8hqzsrghccm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVc2VWbThUY1dEaG4zcHpS
            SXg1Z1FzamZzcXlvejF6SDdGMUJXNmVqdHhZCnFSYlp4c3Mzc2MxUHRqc0crNEFB
            cUpuTXkwNG5TRjFiUC96UFFVQWFwUDAKLS0tIHBaaUQ2MXl5ekpLcktKZDlkM2hw
            MFp5MjBncU9hSTRpVk13STFOWk5jTzAKap8eW5hpNB41+OErhk+TEwq1kSnH6vSg
            R18XqToC5pRTvyTpqtslHLB4HJlO50XHP+MSvTdTW4W5cKqE/YsNow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-12T11:17:34Z"
    mac: ENC[AES256_GCM,data:XJJDP/BkBYIt/kJr5fs5VTPQ8V+GoYNjUaAvCKsYi9iJKQRtyT7AFNpj0ABUYuNtkk0YQLrYrSW7BW4sAQDOjvfn7EF2qIUlZ1B4SiNBjVQKcSL9DAuag3ALFgLXlnWD1H59gESAikqZlcgM4vb36TQsJbhUU8rokJM0zGW10Qg=,iv:z2jRzLJdtz8rm2wrBki5HcWwItiWNoe6mtFUUdI6PCk=,tag:hDbvYh5VvNT+zHhyhmFDhQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
