apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: minio-secret
    namespace: databases
stringData:
    username: ENC[AES256_GCM,data:jOXQJ6M=,iv:ACVzBw9GRSYTVmcyq6Sk1nvjanLA080bhCFfeL+sMAk=,tag:4feXMD4cSX/s0lYk5coacg==,type:str]
    MINIO_PROMETHEUS_TOKEN: ENC[AES256_GCM,data:VoeWCP0=,iv:m5OhX8CE1+svoa/yo0DssVf1A/+IVTXJeDDvXmDpcT0=,tag:j0n2ImJx0q1iPe6d4vWyvQ==,type:str]
    MINIO_ROOT_USER: ENC[AES256_GCM,data:RpaJoq8=,iv:5n8R2hFEDBciPZ1iG+02HePOruYFtvfS1TFcT7Ah7Vs=,tag:KvuIkjYJOrvQ9etGmooPKA==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:Xyj7M842DMs=,iv:MjIDLxgshujGVzVS/5AWVjlYy5W+SdsIkjTX1NT+R6U=,tag:2wVyljgIspB62qqAmQvuxQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18xqz4vdtp26yq4u0u2rkh78w9s3us74d3247a2kcjn9qn4t8hqzsrghccm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVc2VWbThUY1dEaG4zcHpS
            SXg1Z1FzamZzcXlvejF6SDdGMUJXNmVqdHhZCnFSYlp4c3Mzc2MxUHRqc0crNEFB
            cUpuTXkwNG5TRjFiUC96UFFVQWFwUDAKLS0tIHBaaUQ2MXl5ekpLcktKZDlkM2hw
            MFp5MjBncU9hSTRpVk13STFOWk5jTzAKap8eW5hpNB41+OErhk+TEwq1kSnH6vSg
            R18XqToC5pRTvyTpqtslHLB4HJlO50XHP+MSvTdTW4W5cKqE/YsNow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-12T12:39:16Z"
    mac: ENC[AES256_GCM,data:t9pVDHL7Bu7YrsC/TH1PBEcC4B/sSVPgXi+GAqZd41746wRQPLgq6YYZrhfIihT6fPrTb56/3krYqtuWBw1QIqC7QZTESPP2K0jwp9hBhvTkHi4skmxDYAjS6vFYbJ8/4Ucnak4U78V6sVEdBB/twf3H5KX4bDE5ZfwdzBe0EB4=,iv:sVC8NMflxXpq/c+GrM2M3xPqpmtPBONeXEwcE35OR/g=,tag:BSaFk5BdaUI3ySqFfWAK9g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
