apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:V8ioGMvddtLWLpi9BQy/1v3MOkouNLBM7RGtO7YMpfMe2IfFmry5bbYKChrlyFCsR4nEQELdZoddZ5sN,iv:NwfczwCSUqOn4UBxWPutZQUuWnUvhjKHyCcW8FNvdv8=,tag:kpPa2dorVrg8fRlHBp7pzg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18xqz4vdtp26yq4u0u2rkh78w9s3us74d3247a2kcjn9qn4t8hqzsrghccm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEQ0crSjJUQlFnTHBidUti
            ZWdFMU9vM2FFRVRRKzBmOU9VNlpFVGxEK0J3CkRubVRweUs3WlEwa2g5UDJwVTl4
            WkRtY1ZxKzZ3dk92VlN0ckJvdjFJeGcKLS0tIDVCS3o1dERIMXByOWxKeVoyOCth
            QkNPSEZoZXhoZVdwendXM0dFRHI4VEEKx8EFAuAOlwLosp1FZFbJfMBsgUDqOe0Q
            SzDRZ4zyYF+GDZqENxBEqm+zOLUmWQ0t/hf1cHUSsCBVK67DpmP1jg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-12T23:30:31Z"
    mac: ENC[AES256_GCM,data:CijHYcwUOVJS92qujNQNBo1A8SeONf4sdBg7Y3NZopVHt51AaZJ0jRzPwFJ7IIMmOqRD4GAfXGNBFRM2JAsdW9qxoxPRVsT8DMxm9GcvM4BiRhxAli41s6HMWKj4jEEEBwR+HQy3umWQRyuXvypHOSW41dcXwBN0kJ+wBP/MApI=,iv:rydkXaiZwi9+jvuEkV9nn06pS+JvX4GxWrhTqOdG7Rw=,tag:QHSkrYA8DMiEJif/v20R2w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
