apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:okXAKs8/GZnC8s8x3JW8a8gI8KhUqgrHpSXGJbzrctnTE2inns1qKW52BQmSltFfefUKL5VYeOpF4hjo,iv:vWNCrrLz05rbbvWPGN2xORAi4gSMKOM2yP5T/q/xzNQ=,tag:yVSg6JQIQhiiHonMBT3FnQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18xqz4vdtp26yq4u0u2rkh78w9s3us74d3247a2kcjn9qn4t8hqzsrghccm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSdDJqQ085Z0V0alRUUytI
            TndTTEhBbzlBc3l3TkJ2VTVLSFcxSmp2bDBNCjlVMjJYRndGc2t6NUY2RlArZldI
            M3BEYWl5QnNnbG13c2QzTXFqZ21nM0kKLS0tIDVrb29sQmtTY0hxbmxYZUxJMlN4
            TElJRWVzd0loeEZMeWE3UXFQTnBvdkkKYcWLkdIDPprtEQnNYA0bM0SMAtn4+iIx
            zvS8+g/onyi+0vBapjQiLwcdLLHp3Ojqy3qOHSxx5P6kocZVT6OnKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-13T13:03:37Z"
    mac: ENC[AES256_GCM,data:bUz1I9oFCxLNITOkQUpvGsCLLhae7pY//Tx1dnTUjiWnNVZA7I5Xi1T9uKdCga34GvWjOE9uOOKsbiMk6yu9SZIgYjYNL+DuaNNe+I/9KXGL1CUrLjZeBZS/rUkP4zauk88jwwpgW6SyIMpHlaLNTJQ67dBfpKDQnJV0po+zwG0=,iv:Rrzqj32BkncuSKY6nkxLBEyi6lyni69tSbyJlUWhXng=,tag:x3OQP/0JxQyI5TyxH6l2WQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
