apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:mtMKyriLUSoRS4hDzlVl2VEDHJPKL8Qe7Qu7DydJx9vAIwIOQ66/xXmgMedxFzCFNxIxubGGdyeymKeP,iv:CfomZP0Cj3yRMZO8wJOAlsnmy08QeIFeVreLDLozdfE=,tag:4hRoyGWUy6p8JkxolYzvmg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18xqz4vdtp26yq4u0u2rkh78w9s3us74d3247a2kcjn9qn4t8hqzsrghccm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLVU02YU9EN09qNG1yUFBj
            SHVjY1FhOFFDbzNCRXZFRHQ0dEJpcVJSQW1zCmJiazNFZFJ0WGY5K3FNdHJub1lm
            RkZ6MTlwVEtaakZxTENrbDZOaHlMU2sKLS0tIEZLR0lYUStyUHM4aGx3Nld5NHNl
            dlM4bWNDWDNuQzMzTys5dE95VFRRbDgKnsNSXWGyRKa0nQpiuJen8blbP4ZtwysC
            jCfy3ytASjflBU2YoxyE89rBH4kRXLmunYJR5UAJRz6IovhBiMi1gQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-06T22:34:09Z"
    mac: ENC[AES256_GCM,data:N41Cx5rHvzSRDyX/wCwuWnaKeX+vV288Ckn6FOqh6qCN7nnq3g/Tm9QY2kjjYRjO1vFVD8x3BFJTI8o60y92EqHxwm0atmZLSjBAKVnqPURTAw2Z6OObtDVdjr4+Zx9JZDZI86KgrWdr3tsQ9vD4rNTMuiP5fWaQxc6fcFsLIkY=,iv:95HW7aMYFHaKH/jksVIzfqhn2O5F4YoYjX2E44f4J5c=,tag:g8T6RsHwmLReyor5SjzSiw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
