apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:GPOGvdzVJn5wAPRdFHTZ+mnwZ+/xgfwBF6OzK0hJ997Bv5D6MM4gKVjGyAxhDEIkrbznNAdhLQyV7ZaN,iv:IKrNStJTQRAlqtQjPK0ovmn34XiOrXSeT8wffFZSHvM=,tag:Z8XrwA3GvwB6HjbtzSbiOw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18xqz4vdtp26yq4u0u2rkh78w9s3us74d3247a2kcjn9qn4t8hqzsrghccm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5TXMxVlQ3Y0UzOThsd1Nx
            ZWNPNC9hbnNFOE1QNTU5SVlvRUNrcGViaWlvCjcyMytBbUtkSGRFNGlyMWRVWHFn
            Mkh1elhMaER1VFFXYklPT1FodmFpNm8KLS0tIEphS2syTXFwMVQ3RURBTGpRSGJ4
            NzFPVEdBNzN0bnNHUDJ2cnhKQjgwbEEKNal86rgUdESIUoa4LyMiV4diS9/JpBm3
            Z8Q2AUT2Zc5dgpTiKkp5JaVmIwJQaNtQgaJRd+NVLFAAxqXu0BjSdQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-12T22:41:52Z"
    mac: ENC[AES256_GCM,data:g1x9hssWjQJ4v+gP+2SmHE1eA2sBg2NCiKYQ886Am7N6ea2l32u5TOGbRskOkFLz+K3wy9KmXAGubYeo35PY590yBuTU8OkhyBEbGGsSJ7OvaSGmTNBo8K6IGx0/BZHIBRdE2dGWM9vpQlX+BK2j60ehvqYj55O9zXd6YzkLsYg=,iv:ZTcVUP0bUFS7wPg1LNXrWNUunW/xPjg4I5QUNe+RjwI=,tag:8glhL2H6lo294Rdfenm6zA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
