apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:YG+yAb/HvrDl9jK8/8LLTw0Zoi85GAJZjTictbl7fqYED0ijUO+n+Enhseo/VRzL4edwKkZ9mDpRwtwU,iv:dCAf9RaAw6Ns0ex+fe2jra/zKjJCi5hrNSpj4Bj83hU=,tag:8IRZz4kSrhlfsdUuZ5kW1Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18xqz4vdtp26yq4u0u2rkh78w9s3us74d3247a2kcjn9qn4t8hqzsrghccm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZeWQ3c1lkZVgrVEh1Q0VI
            VjZZeGV2bFF1cldielJMZUg0MG1WWHZJL2gwCnUvYjU4NHgzVlRBRFB0Ky9PNFRo
            Vm5yMS9LTmszU0gyNGNXLzBFWk5kRWsKLS0tIGEwblBtdzQyaTJZTWgzSEUraG5T
            L2wvWlhvajJsWXlCYTB6UnBvaXd1Q1EKXMgtEd5LUQ0OZKVaWzJr6WVdQcxyeaTp
            fcWl6puR4FCPkvhwIn6XjdId0GABGtzE5bz6/xF/15twp5ywoX7RvQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-23T13:28:04Z"
    mac: ENC[AES256_GCM,data:3jQc5mJmCO+ZElnQJqLmjRBsemFRMqhyIA7dEoGrdoeXsM9Hu6Q49NMH4E+oUMwVfj0eWi2/g+5NiJugDrjSJoQ1ur1+HnGKklDTuUd+Q+mWU1Y9bx3GvzOrmNKa5fawef354x/s/W3IJwT6Qz7CtS4zRNrH5zD5ejEypfeDlbI=,iv:eUqp0b2K6u1znGXIC3kN32v0SeZYknvsIxqH1Qhm2nw=,tag:netLO+me/rQmiIzAdLZA9A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
