apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:nFHMa9nUcvhCv8frKMk4MG1jYG6imATn+Te3DB1yv5rN3dqH/QBR8bzhlZYHp62pupjHS7CgudpreB50,iv:KAUAcjHTWig/x/Lbv2U/7snmm1zdF+704ocN0DJKX+g=,tag:Sb0NC5nODrgFvo9yZd4n+A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18xqz4vdtp26yq4u0u2rkh78w9s3us74d3247a2kcjn9qn4t8hqzsrghccm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFMjZEaHRIeDhDWEJETy9l
            NVI5bDg3aXplaXo5eFlZYmJ6Ny9VZVJWK0RvCnlyd29DTTRPRmJLSGRGT1phcFBU
            TFozdUFNTFVyeWdwbGxsQ3YwZFlmOEUKLS0tIHU1K2QvcDJYNzR0THZpbmpxd3Q5
            UnpuMmI4L0NRUyttSVg5SjRZQkwweVkKkuF+fF4CP8p4ZEBUJRj8nyKSXucXMY/3
            1x+XOHO/fRtD8QojkhdLsgJcDVK8N8HAsOB5HL2/N8n2Un/mXt4ffw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-07T00:02:56Z"
    mac: ENC[AES256_GCM,data:Bwn31uAXSvtgqxuvKl6D6tbwh4yYIxm7mPcjXyqeumPigLhvvexjJXlXoYOdPZ2U8350tLOeYmDU9ngZl48Vwn4e1x9HqVTHl4XjwZE93w+UM2w5vxABVAw4OPRzUYejEZDO7fnsjbyWRe4riJq4wHqSRWnehW07+dAztwHjB7I=,iv:o2YO7xfXPQi189bbe2+oBUe9UTc9NeERLyALajkn96I=,tag:ab/20+a874Hy6E525cf15Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
