apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:ZkqoRVIkKAkFr9I=,iv:CBZIlooyq0zrKS9btWbGEWV5zPKrSRxTSvokf3+Roak=,tag:C4Yfoqz/LXmWr25mlWjMMA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:AnEzX04/L8cZBfwkW4GRVRBC,iv:1DpPJUGwjZDztwaORZhMe3bmUxrfavXUIQ5MbKQhXo4=,tag:DIOagwSAlLBaUdX8DRLI4g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18xqz4vdtp26yq4u0u2rkh78w9s3us74d3247a2kcjn9qn4t8hqzsrghccm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqZk41amlXS0hkV0t6d1Zq
            bTlZcWdZZkhJdWhPNUNqSTVJaHdEaHR0OGg0CkFwMjNEQ0t5K094bzFzc3VxM084
            dmNTTHVUT28ySmUvUkhHYTlOY0ZGLzQKLS0tIDluSENLeUZ4Z3Vha3JaU2M2aE1r
            TVJ2RjJYUXdwd0hzODJoRFlrWWtJc2cKqf+edNsQC9qAYjP0Fe8EwjzRiD6IgvBk
            NIgMbQXtJ4pytNCA+oXuUT+knc/C8vg9RuqNctIEgXBQ2NGikd0GFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-13T13:03:37Z"
    mac: ENC[AES256_GCM,data:bbeoCGpmcvBIKSm2+865KUg+P48G8PTD1yCZi9gLRAKYYggYc33dsV+Qs8S6JrGULaV7x29JA75Yn5qQAjBP+Kpz+QJS6n5azMzKYJNWDa+X2mwftB6AB7o06Xiw9p8BiFoBXxLBZiE44IfkGIr6XrdRiYf/t4nO4L/iC3yAVbQ=,iv:9yNwJVjGFAGKrpJr4AJJtRbIjFJXs/wwMp+KYHZiVGE=,tag:Q7rwgpgnCMvRpyCuqwM8WQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
