apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:vOoA4/a7zLWtLig=,iv:69bYN2mHxV0rwZ160dfAMNiGbjOEYqzYzAqU5GNKyyQ=,tag:G3lNmE9rCbkvxV1LLshEQA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:yMV1+8LzKPqglxceF3D6yA6u,iv:M4QZyTZRRupAb/5652+cN0KnRxHNOkAkMpWJTi22VM0=,tag:J96aCCVmQThupedug2q2Uw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18xqz4vdtp26yq4u0u2rkh78w9s3us74d3247a2kcjn9qn4t8hqzsrghccm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLeFNtSi9WaFpBRXZVQ2Ns
            TEo4R2RrT2Y3aEt5YzB1SjdpaE9YU0V1TWx3CmVOUHUzeHIrcEZXR2pHOXkyVko5
            aE40TzdCMWNhT2xhOUovejlGdFJTZEEKLS0tIFAwSGU2ZFpNNHVyeUVmWkRMRnRI
            aUVha2ppSzhzc2NmRUl4SlIzNTY5RHcK56077dmVWMLqNbcnrNHm6UfvHQCizTIl
            dvpPoZlGJW2ObPI1SK77D1yJ8gA650etEh+W8Bg40WTVJDDSHuvNkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-06T22:34:08Z"
    mac: ENC[AES256_GCM,data:VOLKtCiqtLvgJ1TAGl5eGN71X7BoAPxUMqKsp0og0MIj/rC6GylmAEHKM2o0miM+/ZnS3rrq8rzvx/JGx3dYw95AhWnlmU2GIvLosaDPS2EKzez7nxpLSk8mgVKj6YWBPvUr/q4o4wLHZnNTjEEt/NpYhl1WkbuxPRoGsvY5dKk=,iv:0PTujhgx9cUus4vZs/mUsEdNZGOtrB1qWoo6XnrHgRo=,tag:+W40++TWBj2behbnLbKyIw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
