apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:PoV8KIDOsZO1qdM=,iv:zNFZlJGVyOpAVvJJFT1XsyFKIZpb+mmwxgprnCXgqB4=,tag:lUWKUN92hh+LBBzHzZlz9A==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:34uARMGTTxjGuudboU0vBJcQ,iv:b6T9IL5CCbefT1/XHXTe/WUuLXHiCBS24AIzCkpx5Jk=,tag:YdQfURIYLMnWE4YJfoerUQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18xqz4vdtp26yq4u0u2rkh78w9s3us74d3247a2kcjn9qn4t8hqzsrghccm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWRFVqWkVzRHcxRmhNME5s
            bmtNYXhLeVcwZUlrY1dJZGt1ZmFpR3VDeG1FClJIb1RaRWZEYlg4SGFMVmNjMzkx
            NWJZU3lSMlQ2TGg2aWUyOWpVN0VTQUEKLS0tIHpuUmhSN2RPZ1NqUXBlWVNtVDVY
            a2tBL0VZT2lCRi9oOHRkL29OMnNnTHMKNHOCKmGsAXhlh9wRScLg8U75oEfWtcCu
            Wzw37QaOUyxXEC3gzWk0tGkl42RMGDKV3+5sf80XvduO5qlGXc0EXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-12T23:30:31Z"
    mac: ENC[AES256_GCM,data:OD1P94mWpcpcMPhP6SOHDJFDRjf3kLjbZ89yRBex98svgX8AZfgGYOK7e1mZv5t4T92yk63Ffim+OgH7jaaH9SfFFPhiQIrJz7vd/uKOl8HQaMSkhxJM/cTvHnVZgH+fzehdgIGiPYWdPJIf9rlAQwwIZgXa61RWVL1cYHbM+l8=,iv:WYv4ZY8LnS/cFasVEBNI3tOISmdbbjQsNNtpJOd4v5Y=,tag:1adAR2lN6djzWGK8oaoa5g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
