apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: storage
spec:
  interval: 15m
  chart:
    spec:
      chart: longhorn
      version: v1.3.2
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: longhorn-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    defaultSettings:
      backupTarget: "nfs://192.168.50.50:/mnt/disks/minio-backup/k3s-longhorn/"
    ingress:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-staging
        hajimari.io/icon: mdi:kubernetes
      hosts:
        - &host "storage.${SECRET_DOMAIN}"
      tls:
        - hosts:
            - *host
          secretName: storage-dashboard-tls
    metricsScraper:
      enabled: true
    serviceMonitor:
      enabled: false
