---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: storage
spec:
  interval: 15m
  chart:
    spec:
      chart: longhorn
      version: v1.3.2
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    env:
      TZ: "${TIMEZONE}"
    defaultSettings:
      backupTarget: "nfs://192.168.50.50:/mnt/disks/minio-backup/k3s-longhorn/"
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-staging
          external-dns.alpha.kubernetes.io/target: "storage.${SECRET_DOMAIN}"
          external-dns.home.arpa/enabled: "true"
          hajimari.io/icon: video-input-antenna
        hosts:
          - host: &host "storage.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: storage-server-tls
