apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-minio
    namespace: databases
stringData:
    username: ENC[AES256_GCM,data:sbHTHA==,iv:45yqofZ54InXpgQESp7MfWvP2kip8kC7DRz0YrvwRbE=,tag:5dQtnqQHyQLrFU5WZMnewA==,type:str]
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:/vYz4cfKW1ANeTccMFIaag==,iv:WWPEa3PkWc+7o2iBQlYepknD38P65pUOSgYhkiQXYN0=,tag:VqoE4Gl63gWCrhU8F5ad4A==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:60rRnUfuySZix/Lb1uHMnJZ942nsb7U/f3oGJ1E75/o=,iv:Ou9ee+CtBqHLL5NPy8TrfjkJHDwNsf4I4sIhGuafzgM=,tag:BZqjyQtVBXahh1074e9U0w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18xqz4vdtp26yq4u0u2rkh78w9s3us74d3247a2kcjn9qn4t8hqzsrghccm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOVTArNksxeWc3b0dXR0ZG
            RXFuZ2xJM3FoWmVPdW1ZOW1LQ2QyRmRHaHg0CkhVdWZ2RTVMczIvOGdEQ2VEV1JS
            NDgveThrOFF1VGFjL3Q0bHY4ZllrVFUKLS0tIDFVY09XM2UwUHFGNXdBQVQ3R0M5
            MStMdDI0YkZKR0dxTTJXUkhhcUhDdlkKepPXvDujZt6TseVj4s9FjsNa/3LzjxjA
            KhuiP8Iu0LYUGw5rZtyML7B9Tnanmo0cmYXcfiFu37KU+OMwFg9Sgw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-23T13:43:15Z"
    mac: ENC[AES256_GCM,data:+Wy6nMNMgAhfX8Z8MKgdwzL3rkjHJl8qoe00RPTK+1e9tSZem0W67fXhM1Ps4Q1YXnu1Lcni8f6j4Zgl/nWHTOaxUfMaXL/j3G+yNCOprlmMpkD/YOPEW7bLKqKSVPFOjjPmyYQN9oe3tbpwMnHU7HCdyaofmA1/ujkfW7SFb2M=,iv:RA3fSPRXf1N6/DrskO6pQ7S3k8dcY/0CUpoCfQCu6ec=,tag:Gk+FWefbCrZDeX+u90IJfQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
