apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: databases
stringData:
    username: ENC[AES256_GCM,data:l3lSCJM=,iv:ISO+lL2309EBYV6P6oX73MLd2qNQ637r83JFRe3Huqk=,tag:UnVXUWQ9ZPI1vXJCW/p8hA==,type:str]
    password: ENC[AES256_GCM,data:hQ5GRGSlZTLehBjJQU6wbA==,iv:GjrubSrILCqP8AteV2uGlHsryIQMSgycGFxLBskeFTM=,tag:6yNKOjdxYu6ZCrCpvVt9Ag==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18xqz4vdtp26yq4u0u2rkh78w9s3us74d3247a2kcjn9qn4t8hqzsrghccm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOVTArNksxeWc3b0dXR0ZG
            RXFuZ2xJM3FoWmVPdW1ZOW1LQ2QyRmRHaHg0CkhVdWZ2RTVMczIvOGdEQ2VEV1JS
            NDgveThrOFF1VGFjL3Q0bHY4ZllrVFUKLS0tIDFVY09XM2UwUHFGNXdBQVQ3R0M5
            MStMdDI0YkZKR0dxTTJXUkhhcUhDdlkKepPXvDujZt6TseVj4s9FjsNa/3LzjxjA
            KhuiP8Iu0LYUGw5rZtyML7B9Tnanmo0cmYXcfiFu37KU+OMwFg9Sgw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-11T09:23:51Z"
    mac: ENC[AES256_GCM,data:omLasFE3C89Zc8cyhI/T09EEwCGCmy17bFBJVYDvnFCH6gmsEQt+BJde+PGupdAn9RAi1Hv+7T2Kv2ej6SNMu2xR0mUh+RnpaLym66Ya/nWMBsfAvvvuGHgySf/37oMiV2IUb2oe3leSRu3GXfbXuKnUavo0x6iiELfUHgFOgFU=,iv:jAnI7QBqndOyOJCEcxExXTKph8dv5yA7gWlpHmAKENg=,tag:stq1iFb84Fzu8mZz46fCKg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
